
package ExemploInterface06;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class FormConjuntodeDados extends javax.swing.JFrame {

    /**
     * Creates new form FormConjuntodeDados
     */
    public FormConjuntodeDados() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarregar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        txtAdicionar = new javax.swing.JTextField();
        scpNomes = new javax.swing.JScrollPane();
        lstNomes = new javax.swing.JList<>();
        cbxNomes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCarregar.setText("Carregar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lstNomes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstNomes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNomesValueChanged(evt);
            }
        });
        scpNomes.setViewportView(lstNomes);

        cbxNomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNomes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomesItemStateChanged(evt);
            }
        });
        cbxNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxNomes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpNomes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cbxNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        
        carregarDados();
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        
        String elem = txtAdicionar.getText();
        
        DefaultListModel m1 = (DefaultListModel)lstNomes.getModel();
        m1.addElement(elem);
        lstNomes.setModel(m1);
        
        //Adicionar o novo elemento ao JComboBox
        DefaultComboBoxModel m2 = (DefaultComboBoxModel)cbxNomes.getModel();
        m2.addElement(elem);
        cbxNomes.setModel(m2);
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void lstNomesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNomesValueChanged
       int idx = lstNomes.getSelectedIndex();
        
        if (idx >= 0) {
        String elem = lstNomes.getSelectedValue();
        JOptionPane.showMessageDialog(null, "Elemento: " + elem + "Posição: " + idx);
    }
    }//GEN-LAST:event_lstNomesValueChanged

    private void cbxNomesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomesItemStateChanged
 
    }//GEN-LAST:event_cbxNomesItemStateChanged

    private void cbxNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomesActionPerformed
               int idx = cbxNomes.getSelectedIndex();
        
        if (idx >= 0) {
        String elem = cbxNomes.getSelectedItem().toString();
        JOptionPane.showMessageDialog(null, "Elemento: " + elem + "\n" + "Posição: " + idx);
    }
    }//GEN-LAST:event_cbxNomesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConjuntodeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConjuntodeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConjuntodeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConjuntodeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConjuntodeDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JComboBox<String> cbxNomes;
    private javax.swing.JList<String> lstNomes;
    private javax.swing.JScrollPane scpNomes;
    private javax.swing.JTextField txtAdicionar;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
this.setTitle("Lista de nomes");
this.setResizable(false);
this.setLocationRelativeTo(null);

lstNomes.setModel(new DefaultListModel());

//Limpar o cpntrole
cbxNomes.setModel(new DefaultComboBoxModel());
carregarDados();
    }
    private void carregarDados(){
        List <String> dados = new ArrayList<>();
        dados.add("Nome 1");
        dados.add("Nome 2");
        dados.add("Nome 3");
        dados.add("Nome 4");
        dados.add("Nome 5");
       
        DefaultListModel m =new DefaultListModel ();
        for(String elem : dados){
            m.addElement(elem);
        }
        lstNomes.setModel(m);
        
        DefaultComboBoxModel c = new DefaultComboBoxModel();
        for(String elem : dados){
            c.addElement(elem);
        }
        cbxNomes.setModel(c);
    }
    
    
}
